### ISSUE TITLE
Adding player lost me weekly points

### ISSUE THREAD

**Issue by cstevens780** [110yards/fantasy#66] opened 2021-09-19 15:18 UTC
Added Odem Gwarchum to replace my DL player(Woodard), Odem isn't assigned a team so it has him as a free agent (plays for BC).  Went to place a waiver for him this week and it immediately executed, which removed the points that my DL already scored  for the week. This took my weekly points from 80.50 points to 78.50 points. It didnt cost me the game but something strange is going on here.

**Comment by mdryden** [comment] 2021-11-13 20:19
Interesting - it's probably related to the fact that those players without teams are in the system.  I'll mark this as a duplicate of issue #40 - the problem should go away once that issue is fixed.

**Closed as completed by mdryden** 2021-11-13 20:19 UTC
Labels: duplicate
