### ISSUE TITLE
Shaq Cooper

### ISSUE THREAD

**Issue by gorillatrain** [110yards/fantasy#216] opened 2022-10-06 18:18 UTC
Shaq Cooper is still listed as having no team. As it is our playoffs it is important that his points gets recognized as hes starting for the Riders this week.

Thanks.

**Comment by mdryden** [comment] 2022-10-11 13:44
Closing this ticket as a duplicate of #218, where more details can be found.

**Closed as completed by mdryden** 2022-10-11 13:44 UTC
