### ISSUE TITLE
BJ Emmons

### ISSUE THREAD

**Issue by argos1873** [110yards/fantasy#215] opened 2022-10-04 13:03 UTC
Just wondering if/when this player will be added to league player lists? 

Been having a fantastic season btw, appreciate how responsive you always are to everyone's concerns 👊🏼

**Comment by mdryden** [comment] 2022-10-11 13:44
Closing this ticket as a duplicate of #218, where more details can be found.

**Closed as completed by mdryden** 2022-10-11 13:44 UTC
Labels: bug 🐞
