### ISSUE TITLE
Points not Appearing

### ISSUE THREAD

**Issue by SteveTaskersSon** [110yards/fantasy#52] opened 2021-08-16 17:26 UTC
Not sure if this bug stems from the same issue as Gwachum from BC.  An owner from my league added Mike Jones this week (WPG DB) and started him.  He registered a tackle but was not given the points for it and it said he was OUT for the game.  See picture below.  

Thanks!

<img width="1410" alt="Screen Shot 2021-08-16 at 12 24 12 PM" src="https://user-images.githubusercontent.com/88464452/129604521-e09de905-0b5a-4cb9-a36a-e5307206f48b.png">

**Comment by mdryden** [comment] 2021-08-16 17:59
This does look related.  In Jones' case, it looks like his ID from the roster page (the one that shows him on Winnipeg) is incorrect, and doesn't match the ID that the CFL is applying stats to (the one which is showing up as having no team.

I will aim to have a fix in for this player issue by the start of this week's games, sorry for the trouble.

**Comment by kamikazecanuck** [comment] 2021-08-16 20:21
Does that mean my Gwachum's points weren't counted too? I won by 1 point but basically it shouldn't have been that close?

**Comment by kamikazecanuck** [comment] 2021-08-16 20:22
No, it's totals right. NM.

**Comment by mdryden** [comment] 2021-08-16 20:38
No the problem with Gwacham is similar but different.

Gwacham has no ID on his roster profile, but he's in the boxscore, he gets created and gets stats anyway.  You have this version of Gwacham on your roster so he works ok (but shows up as having no team)

Jones either has no id on his roster profile, and my fix ended up matching him up to a different Jones, or he has the wrong ID on his profile.  In any case, it's ended with two Jones in the system - one which looks like he's on Winnipeg, but has the wrong ID so doesn't get credit for the points in the boxscore, and one which looks like he's on no team, but gets the points anyway.

Hopefully since Jones had a pretty poor game this week, it didn't affect any results.  If anyone has been hurt by this, hopefully they can let me know.

**Comment by mdryden** [comment] 2021-08-16 20:39
https://github.com/mdryden/110yards-api/issues/88

**Comment by SteveTaskersSon** [comment] 2021-08-16 23:08
It didn't affect the outcome of the the game this week, so no worries there, but I thought I'd bring it to your attention before it potentially does.

Thanks again...I really appreciate the time and effort you put into doing this!

**Comment by mdryden** [comment] 2021-08-18 12:53
@SteveTaskersSon  - I haven't gotten a fix in for this one yet, hoping to have something before Thursday but I'm running out of time.  

Please tell your player that if he's keeping Jones this week, he should drop the Mike Jones that is on his roster currently, and pick up the Mike Jones (DB) that appears to be a Free Agent.  He'll know it's the right Jones because he'll have 7 tackles credited in Week 1, and 1 tackle in Week 2.

Once I have the a fix in place, that version of Jones will be the one that continues to work, and if I don't have a fix in place by tomorrow, it's also the version which will get stats.

**Comment by kamikazecanuck** [comment] 2021-08-19 02:09
Everything still cool with Gwachum? Ike thing I noticed is he doesn’t have the little average points total like everyone else (besides the other issues of not having a team or game…)

**Comment by mdryden** [comment] 2021-08-22 01:48
I think everything is fine with him, he should continue to get stats.  Hoping to have a fix in place for next week.

**Comment by kamikazecanuck** [comment] 2021-08-22 03:04
Actually Gwachum suddenly not counting!This is huge! I need those points!

**Comment by kamikazecanuck** [comment] 2021-08-22 03:05
Oh wait. It’s only when I go to My Team. I think it’s counting on the game page…

**Comment by mdryden** [comment] 2021-08-23 00:00
I've seen this too; there might be a minor bug in the game updates.  I suspect what's happening is very rarely, the site gets a blank response back from the CFL and clears out the scores.  Then on the next update, the data corrects itself.

I need to investigate more but it appears to be minor.

**Comment by mdryden** [comment] 2021-11-13 20:15
Duplicate of https://github.com/mdryden/110yards/issues/40

**Closed as completed by mdryden** 2021-11-13 20:15 UTC
Labels: bug 🐞, duplicate
